#!/bin/sh
export DOTFILES="$HOME/workspace/dotfiles"

alias ..='cd ..'
alias ...='cd ../..'
alias cls='clear'
alias ls='ls --color=auto'
alias ll='ls --color=auto -ahl'
alias k='k -h'
alias python='python3'
alias pip='pip3'
alias tl1='tree -CL 1'
alias tl2='tree -CL 2'
alias tl3='tree -CL 3'
alias tl4='tree -CL 4'
alias caffe='caffeinate'
alias flake88='ln -sf $DOTFILES/conf/flake8 .flake8'
alias dos2unixr='dos2unix $(fd -tf -g "*")'
alias iperf='iperf3'

# makefile
alias mar='make all run'
alias makefile='ln -sf $DOTFILES/makefile'
alias makefile2='cp $DOTFILES/makefile makefile'
# git
alias gdf='git difftool -t vimdiff'
alias gsp='git stash && git pull && git stash pop'
alias gdc='git diff --cached'
alias gfomm='git fetch origin master:master'
alias gfodd='git fetch origin develop:develop'
alias gitflow='git flow'
# tmux
alias tat='tmux attach -t'
alias tkt='tmux kill-session -t'
# etc
alias cdb='compiledb'
alias goaws='ssh -i $ONEDRIVE/key.pem ubuntu@aws'


export RIPGREP_CONFIG_PATH=$DOTFILES/conf/ripgreprc
case "$OSTYPE" in
    darwin*)
        export PATH=/opt/homebrew/bin:$PATH
        export JAVA_HOME=/opt/homebrew/opt/openjdk
        export ONEDRIVE="$HOME/Library/CloudStorage/OneDrive-개인/"
        ;;
    linux*)
        export PATH=$HOME/.local/bin:$PATH
        if grep -q -Irin microsoft /proc/version; then  # WSL
            alias open='explorer.exe'
        else  # Native
            alias open='xdg-open'
        fi
        ;;
esac

WORKSPACE=$HOME/workspace
if [ -d $WORKSPACE ] && [ $PWD = $HOME ]; then
    cd $WORKSPACE
fi

# pyenv
if command -v pyenv 1>/dev/null 2>&1; then
    eval "$(pyenv init -)"
fi

# unsetopt BG_NICE

export USE_CCACHE=1
export CLICOLOR=1
export FZF_DEFAULT_COMMAND="fd --type f"
export FZF_DEFAULT_OPTS='--color=fg:#f8f8f2,bg:#282a36,hl:#bd93f9 --color=fg+:#f8f8f2,bg+:#44475a,hl+:#bd93f9 --color=info:#ffb86c,prompt:#50fa7b,pointer:#ff79c6 --color=marker:#ff79c6,spinner:#ffb86c,header:#6272a4'
