#!/bin/sh
export DOTFILES="$HOME/workspace/dotfiles"

alias ..='cd ..'
alias ...='cd ../..'
alias cls='clear'
alias ls='ls --color=auto'
alias ll='ls --color=auto -hl'
alias k='k -h'
alias vi='nvim'
alias nvim.='nvim .'
alias python='python3'
alias pip='pip3'
alias gdf='git difftool -t vimdiff'
alias gsp='git stash && git pull && git stash pop'
alias ff='find . -type f -iname'
alias tl1='tree -L 1'
alias tl2='tree -L 2'
alias tl3='tree -L 3'
alias tl4='tree -L 4'
alias makefile='ln -sf $DOTFILES/makefile'
alias makefile2='cp $DOTFILES/makefile makefile'
alias makefile3='echo include $DOTFILES/makefile >> makefile'
alias flake88='ln -sf $DOTFILES/conf/flake8 .flake8'
# alias dos2unixr='find . -type f -print0 | xargs -0 dos2unix'
alias dos2unixr='dos2unix $(find . -type f -not -path "*.git/*")'
alias iperf='iperf3'
alias ycm='python ~/.vim/plugged/youcompleteme/install.py --clang-completer'
alias gdc='git diff --cached'
alias gitflow='git flow'
alias cmakefile='ln -sf $DOTFILES/CMakeLists.txt'
alias cmakeclean='rm -rf CMakeCache.txt CMakeFiles cmake_install.cmake'
alias mar='make all run'

export FZF_DEFAULT_COMMAND="fd --type f"
export FZF_DEFAULT_OPTS=$FZF_DEFAULT_OPTS'
--color=fg:#f8f8f2,bg:#282a36,hl:#bd93f9
--color=fg+:#f8f8f2,bg+:#44475a,hl+:#bd93f9
--color=info:#ffb86c,prompt:#50fa7b,pointer:#ff79c6
--color=marker:#ff79c6,spinner:#ffb86c,header:#6272a4'

case "$OSTYPE" in
    darwin*)
        export PATH=/opt/homebrew/bin:$PATH
        ;;
    linux*)
        if grep -q -Irin microsoft /proc/version; then
            # WSL
            alias open='explorer.exe'
        else
            # native
            alias open='xdg-open'
        fi
        ;;
esac

WORKSPACE=$HOME/workspace
if [ -d $WORKSPACE ] && [ $PWD = $HOME ]; then
    cd $WORKSPACE
fi

export USE_CCACHE=1

# API Key
case "$OSTYPE" in
    darwin*)
        export ACCESS_KEY='hmCpEbHz9GVK2LfTkxWY7A8PgCJUs7TjgqwSsUEH'
        export SECRET_KEY='9uaCZwQ2Bp4cIXaz5jp1CvGg4Ury4UT3GN77LGl0'
        ;;
    linux*)
        export ACCESS_KEY='oyoSSj4IagMUWSLIo8wPMpfxpqE79HWxEF3IswOV'
        export SECRET_KEY='QRNhzgU9gH2wBFI5xVG57YRq4o7pSW5xUnxXVPQr'
        ;;
esac
