#!/bin/bash

DOTFILES=$HOME/workspace/dotfiles

ln -sf $DOTFILES/vimrc $HOME/.vimrc

if [ ! -d $HOME/.vim/after ]; then
    ln -sf $DOTFILES/conf/vim-after $HOME/.vim/after
    echo Make .vim/after symlink
else
    echo after dir already exists
fi

# Vundle & Plugin install
if [ ! -d ~/.vim/bundle/Vundle.vim ]; then
    echo -e "cloning Vundle\n"
    git clone https://github.com/gmarik/Vundle.vim.git ~/.vim/bundle/Vundle.vim > /dev/null
else
    echo Vundle already exists
fi

vim +PluginInstall +qall
