#!/bin/bash

if [ ! -x $(which pip3) ]; then
    if [[ $OSTYPE == linux* ]]; then
        echo -e "\nInstall pip3 first"
        sudo apt-get install python3-pip
    fi
fi

echo -e "\nInstall python packages"

while read line
do
    echo -e "\n[Install & Upgrade $line]"
    python3 -m pip install -U --user $line
done < <(cat << EOF
    pip
    flake8
    autopep8
    numpy
    scipy
    matplotlib
    pyqt5
EOF
)

echo -e "\nComplete\n"
