#!/bin/bash

CONF=$HOME/workspace/dotfiles/conf

TAR=$HOME/.ctags.d/default.ctags
if [ ! -e $TAR ]; then
    mkdir -p $(dirname $TAR)
    ln -sf $CONF/ctags $TAR
    echo Make universal-ctags symlink
else
    echo default.ctags already exists
fi

# exuberant-ctags
ln -sf $CONF/ctags $HOME/.ctags
ln -sf $CONF/ackrc $HOME/.ackrc
ln -sf $CONF/flake8 $HOME/.flake8
