#!/bin/bash

CONF=$HOME/workspace/dotfiles/conf
DOTFILES=$HOME/workspace/dotfiles

TAR=$HOME/.ctags
if [ ! -e $TAR ]; then
    ln -sf $CONF/ctags $TAR
    echo Make exuberant-ctags symlink
else
    echo .ctags already exists
fi

TAR=$HOME/.ctags.d/default.ctags
if [ ! -e $TAR ]; then
    mkdir -p $(dirname $TAR)
    ln -sf $CONF/ctags $TAR
    echo Make universal-ctags symlink
else
    echo default.ctags already exists
fi

ln -sf $CONF/ackrc $HOME/.ackrc
